name: Trigger Azure ML Job

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  run_azure_ml_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4


      # Step 2: Azure CLI Login using the service principal credentials
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        

      # Step 4: Submit the Azure ML Job using the job.yml
      - name: Submit Azure ML Job using CLI
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az extension add --name ml
            az ml job run submit --file ./src/model/job.yml
