name: Trigger Azure ML Job

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  run_azure_ml_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          azcliversion: 2.0.72

      # Step 3: Azure CLI Login using the service principal credentials
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        

      # Step 4: Submit the Azure ML Job using the job.yml
      - name: Submit Azure ML Job
        run: |
          az ml job run submit --file ./src/model/job.yml
