name: Trigger Azure ML Job

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  run_azure_ml_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1

      # Step 3: Azure CLI Login using the service principal credentials
      - name: Azure CLI Login
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > az_credentials.json
          az login --service-principal --username $(jq -r .clientId az_credentials.json) --password $(jq -r .clientSecret az_credentials.json) --tenant $(jq -r .tenantId az_credentials.json)
        
      # Step 4: Install Azure Machine Learning CLI Extension
      - name: Install Azure ML CLI Extension
        run: |
          az extension add --name ml

      # Step 5: Submit the Azure ML Job using the job.yml
      - name: Submit Azure ML Job
        run: |
          az ml job run submit --file ./src/model/job.yml
