name: Deploy AQI Prediction Model to Azure ML

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure ML
      run: |
        az ml model register --model-path model.pkl --name aqi-prediction-model --workspace-name newWorkspace --resource-group newResource
        az ml endpoint create -f endpoint_config.yml --workspace-name newWorkspace --resource-group newResource
